---
galaxy_info:
  role_name: capistrano
  company: Princeton University Library
  description: Capistrano Role
  author: pulibrary

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - bionic
dependencies:
  - role: 'pulibrary.deploy_user'
  - role: 'pulibrary.ruby'
