---
galaxy_info:
  role_name: deploy_user
  author: pulibrary
  description: Role to set up a deploy user on a server
  company: Princeton University Library

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Ubuntu
      versions:
        - bionic

dependencies:
  - role: 'pulibrary.common'
